name:                tape
version:             0.5.0.0
github:              "joedaws/tape"
license:             BSD-3-Clause
author:              "Joseph Daws, Jr."
maintainer:          "jozzef@hey.com"
copyright:           "2025"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/joedaws/tape#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- lens
- text
- brick
- microlens
- microlens-th
- microlens-mtl
- vty
- vty-crossplatform

ghc-options:
- -threaded
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  tape:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tape

tests:
  tape-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tape

  lint:
    main:                HLint.hs
    source-dirs:         lint
    dependencies:
    - hlint
